### ISSUE TITLE
Leave Lobby: As a joining user, I want to be able to leave the game lobby in case I don’t want to continue 

### ISSUE THREAD

**Issue by laendi22** [sopra-fs24-group-46/server#9]
**Acceptance criteria:** 
- [x] sopra-fs24-group-46/client#60
- [x] sopra-fs24-group-46/client#19
- [x] sopra-fs24-group-46/client#20
- [x] sopra-fs24-group-46/client#15

**Comment by S3r4f1n** [comment]
Closed in :9c0d2b1

**Comment by S3r4f1n** [comment]
close since all tasks are done
